parameters:
#    irvyne_zurb_foundation.example.class: Irvyne\ZurbFoundationBundle\Example

services:
#    irvyne_zurb_foundation.example:
#        class: %irvyne_zurb_foundation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
